name: Release

env:
  PROJECT_NAME: deduplicator
  PROJECT_DESC: "Filter, Sort & Delete Duplicate Files Recursively"
  PROJECT_AUTH: "sreedevk"

on:
  release:
    types:
      - created

jobs:
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: deduplicator
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
